### ISSUE TITLE
Import Network

### ISSUE THREAD

**Issue by kirsten12** [c3di/neuroscope#1]
Dear,

I was wondering how long it takes to load my own trained U-net, (.h5 file, 363 mb) into the toolbox? 
It currently seems to be stuck at loading the file for me, even if I let it load for a couple of hours. Is there something I could do to speed it up? 
I have no loading problems with the included examples. 

Thanks in advance.

**Comment by Max-ChenFei** [comment]
It will takes few seconds to load the model into the toolbox. I think should be something wrong. The source code is uploaded, maybe it could be helpful.

**Comment by Max-ChenFei** [comment]
Or can you share your trained u-net?

**Comment by kirsten12** [comment]
Thanks for the reply! I will share the file with you through e-mail.

**Comment by Max-ChenFei** [comment]
You're welcome.

**Comment by OliverZar** [comment]
Hi! I am trying to load my model to the executable, with architectures like VGG16 and VGG19 and it does not finish loading the model. Is there any solution?
With the executable, it does load the examples, but it does not finish loading the model that I select locally.
