### ISSUE TITLE
Resolve Package No tFound: 

### ISSUE THREAD

**Issue by rezadarooei** [c3di/neuroscope#4]
based on gpu.yml I want to create an environment what should I do? do you have any plan to update yml file?

Resolve Package Not Found: 
  - grpcio==1.23.0=py36h3db2c7e_0
  - libtiff==4.1.0=h21b02b4_3
  - protobuf==3.11.2=py36he025d50_0
  - m2w64-gcc-libs-core==5.3.0=7
  - tensorflow==1.13.1=h21ff451_8
  - icu==64.2=he025d50_1
  - xz==5.2.4=h2fa13f4_1001
  - jpeg==9c=hfa6e2cd_1001
  - tensorflow-base==1.13.1=py36_8
  - pillow==7.0.0=py36h9ea1dd6_0
  - kiwisolver==1.1.0=py36he980bc4_0
  - libxslt==1.1.33=heafd4d3_0
  - libiconv==1.15=hfa6e2cd_1005
  - pyreadline==2.1=py36_1001
  - m2w64-gmp==6.1.0=2
  - tk==8.6.10=hfa6e2cd_0
  - markupsafe==1.1.1=py36hfa6e2cd_0
  - keras==2.3.1=py36h21ff451_0
  - ninja==1.9.0=h1ad3211_1
  - libpng==1.6.37=h7602738_0
  - lz4-c==1.8.3=he025d50_1001
  - graphviz==2.38.0=h6538335_1011
  - scipy==1.3.1=py36h29ff71c_0
  - matplotlib-base==3.1.2=py36h2981e6d_1
  - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
  - intel-openmp==2019.5=281
  - qt==5.12.5=h7ef1ec2_0
  - zstd==1.4.4=hd8a0e53_1
  - libclang==9.0.1=default_hf44288c_0
  - pyqt==5.12.3=py36h6538335_1
  - cffi==1.13.2=py36hb32ad35_0
  - pygpu==0.7.6=py36hc8d92b1_1000
  - h5py==2.10.0=nompi_py36h422b98e_101
  - msys2-conda-epoch==20160418=1
  - yaml==0.2.2=hfa6e2cd_1
  - icc_rt==2019.0.0=h0cc432a_1
  - python==3.6.8=h9f7ef89_0
  - freetype==2.10.0=h563cfd7_1
  - libprotobuf==3.11.2=h1a1b453_0
  - mkl-service==2.3.0=py36hfa6e2cd_0
  - libxml2==2.9.10=h9ce36c8_0
  - m2w64-gcc-libs==5.3.0=7
  - pyyaml==5.2=py36hfa6e2cd_0
  - hdf5==1.10.5=nompi_ha405e13_1104
  - pyside2==5.13.1=py36hfa7ce6d_6
  - tornado==6.0.3=py36hfa6e2cd_0
  - zlib==1.2.11=h2fa13f4_1006
  - openssl==1.1.1d=hfa6e2cd_0
  - vc=14.1
  - sqlite==3.30.1=hfa6e2cd_0
  - libgpuarray==0.7.6=hfa6e2cd_1003
  - m2w64-gcc-libgfortran==5.3.0=6
  - numpy==1.17.3=py36hc71023c_0
  - pytorch==1.3.1=py3.6_cuda101_cudnn7_0
  - vs2015_runtime
  - wincertstore==0.2=py36_1003
  - tensorflow-estimator==1.13.0=py36h39e3cac_0

**Comment by aghand0ur** [comment]
any update on this issue @Max-ChenFei @rezadarooei @?
cc @PhD-AKG92

similar behavior for cpu yml too:
```
ResolvePackageNotFound: 
  - vs2015_runtime
  - vc=14.1
  - wincertstore==0.2=py36h7fe50ca_0
  - python==3.6.8=h9f7ef89_0
```

**Comment by dmitrii-badretdinov** [comment]
The strict versioning of the packages was done in order to prevent bugs.
Turns out that some package versions are not kept indefinitely.
You can relax the package requirements, although I suggest to keep them as close as possible to the specified versions.
