### ISSUE TITLE
Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by abdulkarimgizzini** [c3di/neuroscope#6]
Dear Fei Chen,

I would like first to congratulate you on this impressive work!
Recently, I was working on reproducing your results, however, the provided .h5 models (classification and segmentation) are not working when loaded into the Neuroscope toolbox.
I checked all the .h5 models using the h5debug tool and I got (cannot open file). This debugging ensures that all the .h5 files included in the examples directory are not working.
Could you please update the examples folder by uploading a new working version of all the used models?

--
Best regards,
Abdul Karim GIZZINI
_____________________________________________________
Postdoctoral Researcher
ETIS UMR 8051, CY Cergy Paris University, ENSEA, CNRS
6 avenue du Ponceau - 95014 CERGY PONTOISE CEDEX, France
Website: https://abdulkarimgizzini.org/
Email: abdulkarim.gizzini@ensea.fr

**Comment by Max-ChenFei** [comment]
Dear Abdul,

Thanks for your interest.

I will fix this issue as soon as possible.

best regards
Fei

**Comment by abdulkarimgizzini** [comment]
Dear Fei Chen,
Thank you very much for your reply.
I will be very grateful if you can inform me once the models are uploaded.
Another question if you please, Neuroscope supports PyTorch right?
Because also when I tried to upload .pth model to the NEuroscope tool I get
"Model not supported". Could you please give me more details?
Looking Forward to your reply.
--
Best regards,
Abdul Karim GIZZINI
_____________________________________________________
Postdoctoral Researcher
ETIS UMR 8051, CY Cergy Paris University, ENSEA, CNRS
6 avenue du Ponceau - 95014 CERGY PONTOISE CEDEX, France
Website: https://abdulkarimgizzini.org/

**Comment by Max-ChenFei** [comment]
Dear Abdul,

I load the h5 model from the example folder into Neuroscope toolbox., It works. 

Could you please tell me the error when you load the model?

best regards
Fei

**Comment by Max-ChenFei** [comment]
Yes, sure, we support pt file format for the Pytorch model. An example named `fcn_resnet101.pt` is in `example/segmentation` folder.

**Comment by abdulkarimgizzini** [comment]
> Dear Abdul,
> 
> I load the h5 model from the example folder into Neuroscope toolbox., It works.
> 
> Could you please tell me the error when you load the model?
> 
> best regards Fei

Kindly, find below the error when trying to load the vgg16.h5 model
![NeuroscopeError_Loading_Models](https://user-images.githubusercontent.com/78584545/186507092-3d0ae44b-ff5d-45b3-86f1-8b29030f2901.png)


Best regards,
Abdul Karim GIZZINI
cc @aghand0ur

**Comment by Max-ChenFei** [comment]
Dear Abdul,

We release one executable (https://github.com/c3di/neuroscope/releases/tag/v1.0). I download this executable and I am able to load the model.

I found there are some conflicts when installing anaconda packages. I will fix it soon.

**Comment by Max-ChenFei** [comment]
We have different channels where the packages are stored for example `conda-forge, anaconda, default`. In our case, we should not set the priority of the channels before creating the environment.

**Comment by Parth527** [comment]
Hi Max-ChenFei,

Thank you for your amazing work. I downloaded the executable but it throws the path error and cannot open the .exe.
Can you please assist?

Kind Regards,
Parth
